/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuadrantesRouteImport } from './routes/quadrantes'
import { Route as OperadoresRouteImport } from './routes/operadores'
import { Route as MonitoresRouteImport } from './routes/monitores'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as CsvRouteImport } from './routes/csv'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as IndexRouteImport } from './routes/index'

const QuadrantesRoute = QuadrantesRouteImport.update({
  id: '/quadrantes',
  path: '/quadrantes',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadoresRoute = OperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoresRoute = MonitoresRouteImport.update({
  id: '/monitores',
  path: '/monitores',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvRoute = CsvRouteImport.update({
  id: '/csv',
  path: '/csv',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/cadastro': typeof CadastroRoute
  '/csv': typeof CsvRoute
  '/historico': typeof HistoricoRoute
  '/monitores': typeof MonitoresRoute
  '/operadores': typeof OperadoresRoute
  '/quadrantes': typeof QuadrantesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/cadastro': typeof CadastroRoute
  '/csv': typeof CsvRoute
  '/historico': typeof HistoricoRoute
  '/monitores': typeof MonitoresRoute
  '/operadores': typeof OperadoresRoute
  '/quadrantes': typeof QuadrantesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/cadastro': typeof CadastroRoute
  '/csv': typeof CsvRoute
  '/historico': typeof HistoricoRoute
  '/monitores': typeof MonitoresRoute
  '/operadores': typeof OperadoresRoute
  '/quadrantes': typeof QuadrantesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avaliacao'
    | '/cadastro'
    | '/csv'
    | '/historico'
    | '/monitores'
    | '/operadores'
    | '/quadrantes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacao'
    | '/cadastro'
    | '/csv'
    | '/historico'
    | '/monitores'
    | '/operadores'
    | '/quadrantes'
  id:
    | '__root__'
    | '/'
    | '/avaliacao'
    | '/cadastro'
    | '/csv'
    | '/historico'
    | '/monitores'
    | '/operadores'
    | '/quadrantes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  CadastroRoute: typeof CadastroRoute
  CsvRoute: typeof CsvRoute
  HistoricoRoute: typeof HistoricoRoute
  MonitoresRoute: typeof MonitoresRoute
  OperadoresRoute: typeof OperadoresRoute
  QuadrantesRoute: typeof QuadrantesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quadrantes': {
      id: '/quadrantes'
      path: '/quadrantes'
      fullPath: '/quadrantes'
      preLoaderRoute: typeof QuadrantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadores': {
      id: '/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof OperadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitores': {
      id: '/monitores'
      path: '/monitores'
      fullPath: '/monitores'
      preLoaderRoute: typeof MonitoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv': {
      id: '/csv'
      path: '/csv'
      fullPath: '/csv'
      preLoaderRoute: typeof CsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  CadastroRoute: CadastroRoute,
  CsvRoute: CsvRoute,
  HistoricoRoute: HistoricoRoute,
  MonitoresRoute: MonitoresRoute,
  OperadoresRoute: OperadoresRoute,
  QuadrantesRoute: QuadrantesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
